version: '3.1'
services:
  springboot-app:
     container_name: springboot-app
     image: springboot-app
     build: .
     restart: always
     depends_on:
       - mysqldb
     ports:
      - 8080:8080
     environment:
        MYSQL_HOST: mysqldb
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASSWORD: " "

  mysqldb:
     container_name: mysqldb
     image: mysql
     ports:
      - 3307:3306
     environment:
        MYSQL_DATABASE: productdb
        MYSQL_ALLOW_EMPTY_PASSWORD: " "